INSERT INTO athlete (fname, lname, username, password) VALUES ('test', 'test', 'test', 'test');
INSERT INTO athlete (fname, lname, username, password) VALUES ('Shen Nan', 'Wong', 'wongshennan', '3627909a29c31381a071ec27f7c9ca97726182aed29a7ddd2e54353322cfb30abb9e3a6df2ac2c20fe23436311d678564d0c8d305930575f60e2d3d048184d79');


INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (1, 'Running', '8/8/2021', '8:21', 'Singapore Running', '7.97', 562, '0:41:00', '161', '178', '4.4', '170', '180', '5:09', '3:51', '43', '52', 1.14, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '41:00.1', 1, '0:40:59', '0:44:44', '2', '37', 1) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (2, 'Running', '7/28/2021', '23:34', 'Singapore Running', '6.82', 478, '0:47:20', '139', '166', '3.4', '133', '179', '6:56', '4:15', '57', '30', 1.16, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '01:30.0', 7, '0:47:03', '0:47:20', '9', '39', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (3, 'Running', '7/21/2021', '11:24', 'Singapore Running', '4.39', 337, '0:26:57', '151', '166', '3.3', '163', '250', '6:08', '4:13', '2', '4', 1, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '26:56.9', 1, '0:26:55', '0:28:33', '3', '7', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (4, 'Running', '7/18/2021', '12:41', 'Singapore Running', '2.41', 156, '0:12:08', '150', '174', '2.6', '174', '241', '5:02', '3:39', '12', '9', 1.14, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '12:07.8', 1, '0:12:08', '0:12:08', '-7', '4', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (5, 'Running', '7/5/2021', '21:47', 'Singapore - Tempo', '8.86', 567, '0:46:04', '150', '171', '3.7', '165', '197', '5:12', '3:49', '12', '13', 1.15, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '00:03.7', 9, '0:45:32', '0:48:30', '3', '8', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (6, 'Running', '7/3/2021', '7:54', 'Singapore - Endurance', '7.89', 494, '0:57:31', '128', '163', '2.9', '141', '181', '7:17', '4:18', '20', '30', 0.97, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '12:31.5', 2, '0:56:01', '0:57:47', '18', '34', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (7, 'Running', '6/28/2021', '9:50', 'Singapore - Tempo', '6.44', 409, '0:33:02', '150', '168', '3.3', '166', '182', '5:08', '3:35', '7', '11', 1.16, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '00:02.0', 6, '0:32:57', '0:33:09', '--', '6', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (8, 'Walking', '6/27/2021', '23:33', 'Singapore Walking', '6.37', 362, '1:17:53', '81', '110', '0.3', '108', '241', '12:13', '6:01', '10', '10', 0.76, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '04:55.1', 7, '1:15:22', '1:17:53', '-28', '-21', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (9, 'Virtual Cycling', '6/24/2021', '9:23', 'Zwift - HOUR OF POWER', '14.36', 253, '0:30:08', '--', '--', '--', '--', '--', '28.6', '66', '84', '--', 0, 0, 0, '83', '117', '168', '157', '146', '534', '--', '--', '--', '00:02.0', 29, '0:30:00', '0:30:07', '4', '65', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (10, 'Walking', '6/22/2021', '7:51', 'Singapore Walking', '4.08', 240, '0:57:08', '80', '104', '0.2', '93', '128', '14:00', '7:54', '3', '5', 0.77, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '01:14.1', 5, '0:53:02', '0:57:08', '-51', '-45', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (11, 'Running', '6/21/2021', '10:23', 'Singapore - Tempo', '9.03', 554, '1:02:09', '135', '170', '3.3', '138', '228', '6:53', '3:53', '58', '23', 0.99, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '01:30.0', 7, '1:01:28', '1:05:53', '-44', '-8', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (12, 'Virtual Cycling', '6/15/2021', '19:08', 'Zwift - HOUR OF POWER', '27.27', 425, '0:52:05', '--', '--', '--', '--', '--', '31.4', '52.1', '40', '--', 0, 0, 0, '87', '121', '157', '155', '142', '551', '--', '--', '--', '00:10.0', 24, '0:51:56', '0:52:10', '4', '143', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (13, 'Running', '6/13/2021', '10:36', 'Singapore Running', '6.23', 395, '0:30:21', '153', '170', '3.3', '174', '230', '4:52', '4:05', '7', '4', 1.18, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '30:21.5', 1, '0:30:14', '0:33:37', '3', '9', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (14, 'Cycling', '6/12/2021', '7:21', 'Singapore Cycling', '34.18', 479, '1:07:31', '121', '152', '1.9', '--', '--', '30.4', '44.4', '140', '167', 0, 0, 0, '91', '125', '--', '--', '--', '--', '5643', '--', '--', '08:49.2', 7, '1:06:59', '1:09:36', '-15', '16', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (15, 'Running', '6/11/2021', '10:45', 'Singapore Running', '7.07', 445, '0:37:36', '146', '173', '3.3', '163', '247', '5:19', '4:04', '11', '8', 1.14, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '00:32.7', 12, '0:37:33', '0:37:36', '5', '12', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (16, 'Virtual Cycling', '6/8/2021', '19:01', 'Zwift - HOUR OF POWER', '32.05', 484, '0:58:58', '--', '--', '--', '--', '--', '32.6', '46.5', '48', '--', 0, 0, 0, '85', '136', '169', '171', '143', '599', '--', '--', '--', '00:10.0', 26, '0:56:20', '0:59:27', '2', '284', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (17, 'Running', '6/7/2021', '7:04', 'Singapore - Endurance', '4.03', 224, '0:18:51', '142', '164', '2.7', '177', '181', '4:40', '3:50', '11', '11', 1.21, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '00:09.2', 5, '0:18:50', '0:18:51', '15', '24', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (18, 'Running', '6/6/2021', '8:55', 'Singapore - Endurance', '10', 636, '0:47:44', '158', '168', '4.2', '175', '184', '4:46', '3:52', '22', '17', 1.2, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '00:01.2', 11, '0:47:41', '0:48:33', '-6', '5', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (19, 'Virtual Cycling', '6/5/2021', '10:41', 'Zwift - NYC', '21.41', 372, '1:00:16', '--', '--', '--', '--', '--', '21.3', '74.4', '366', '--', 0, 0, 0, '82', '111', '119', '124', '107', '324', '--', '--', '--', '00:16.0', 1, '1:00:11', '1:00:46', '4', '133', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (20, 'Virtual Cycling', '6/4/2021', '18:57', 'Zwift - WATT BOMB VO2', '25.93', 441, '1:01:59', '--', '--', '--', '--', '--', '25.1', '48.7', '97', '--', 0, 0, 0, '87', '144', '164', '170', '126', '592', '--', '--', '--', '00:10.0', 39, '0:58:17', '1:01:56', '-6', '16', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (21, 'Walking', '6/4/2021', '10:52', 'Singapore Walking', '6', 352, '1:07:47', '97', '112', '0.4', '115', '135', '11:18', '7:27', '13', '4', 0.77, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '00:04.3', 7, '1:05:47', '1:07:47', '3', '13', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (22, 'Virtual Cycling', '6/1/2021', '19:31', 'Zwift - London', '10.36', 139, '0:21:49', '--', '--', '--', '--', '--', '28.5', '44', '32', '--', 0, 0, 0, '86', '105', '116', '114', '111', '181', '--', '--', '--', '21:48.1', 1, '0:21:43', '0:21:47', '11', '31', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (23, 'Indoor Cycling', '6/1/2021', '19:04', 'Indoor Cycling', '0', 481, '0:50:37', '138', '157', '2.9', '--', '--', '--', '--', '--', '--', 0, 0, 0, '87', '111', '--', '--', '--', '--', '3916', '--', '--', '50:37.1', 1, '0:00:00', '0:50:42', '--', '--', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (24, 'Virtual Cycling', '6/1/2021', '19:01', 'Zwift - HOUR OF POWER', '13.26', 238, '0:29:20', '--', '--', '--', '--', '--', '27.1', '48.4', '112', '--', 0, 0, 0, '77', '129', '168', '168', '142', '427', '--', '--', '--', '00:10.0', 8, '0:25:54', '0:29:26', '12', '116', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (25, 'Running', '6/1/2021', '11:40', 'Singapore Running', '5.56', 343, '0:27:07', '156', '178', '3.1', '165', '200', '4:53', '3:37', '16', '12', 1.22, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '01:30.0', 8, '0:26:23', '0:41:32', '4', '12', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (26, 'Running', '6/1/2021', '11:22', 'Singapore Running', '1.88', 122, '0:10:14', '143', '156', '2.2', '159', '179', '5:26', '4:13', '2', '3', 1.16, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '04:45.7', 2, '0:09:44', '0:10:14', '3', '7', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (27, 'Running', '5/30/2021', '8:42', 'Singapore Running', '10', 644, '0:49:32', '156', '173', '4.3', '173', '179', '4:57', '4:02', '5', '12', 1.17, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '00:00.9', 11, '0:49:29', '0:49:32', '19', '30', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (28, 'Pool Swimming', '5/27/2021', '21:00', 'Pool Swimming', '1,450', 334, '0:58:37', '--', '--', '--', '--', '--', '2:10', '0:19', '--', '--', 0, 0, 0, '--', '--', '--', '--', '--', '--', '723', '90', '23', '00:01.1', 33, '0:31:18', '1:28:07', '--', '--', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (29, 'Running', '5/27/2021', '18:09', 'Singapore - Endurance', '7.69', 440, '0:38:38', '143', '164', '3.3', '171', '203', '5:01', '3:57', '7', '14', 1.16, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '03:18.3', 8, '0:38:27', '0:41:27', '16', '53', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (30, 'Running', '5/26/2021', '18:43', 'Singapore - Tech + Speed End', '4.74', 241, '0:32:51', '125', '151', '2.1', '116', '223', '6:56', '2:25', '13', '21', 1.16, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '00:01.3', 37, '0:27:23', '0:37:53', '12', '37', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (31, 'Running', '5/24/2021', '17:44', 'Singapore Running', '7.15', 511, '0:41:48', '151', '166', '3.6', '165', '228', '5:51', '3:31', '8', '5', 1.03, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '00:39.7', 8, '0:41:05', '0:41:48', '3', '8', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (32, 'Running', '5/24/2021', '8:49', 'Singapore - Tempo', '5.84', 360, '0:30:01', '148', '170', '3.3', '160', '182', '5:08', '3:41', '14', '14', 1.18, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '00:01.2', 13, '0:29:26', '0:31:08', '26', '35', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (33, 'Running', '5/19/2021', '8:29', 'Singapore Running', '6.13', 385, '0:30:02', '157', '181', '3.5', '164', '231', '4:54', '3:42', '11', '11', 1.22, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '00:01.7', 13, '0:29:54', '0:33:44', '3', '8', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (34, 'Running', '5/18/2021', '9:35', 'Singapore Running', '3.73', 332, '1:02:35', '102', '159', '2.2', '36', '177', '16:46', '4:33', '39', '10', 3.14, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '05:16.4', 4, '0:39:06', '1:02:35', '-5', '29', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (35, 'Running', '5/15/2021', '7:53', 'Singapore - Endurance', '5.48', 411, '0:34:20', '151', '171', '3.2', '159', '177', '6:16', '4:33', '10', '8', 1, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '03:49.1', 6, '0:34:18', '0:37:38', '-6', '8', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (36, 'Running', '5/12/2021', '19:37', 'Singapore Running', '4.16', 229, '0:20:01', '142', '170', '2.9', '163', '225', '4:48', '3:35', '4', '7', 1.24, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '01:00.0', 8, '0:19:58', '0:20:16', '20', '25', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (37, 'Running', '4/25/2021', '7:54', 'Singapore Running', '11', 827, '1:09:03', '155', '173', '3.6', '161', '209', '6:17', '5:04', '12', '19', 0.99, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '03:18.9', 11, '1:09:01', '1:09:03', '15', '25', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (38, 'Running', '4/22/2021', '7:27', 'Singapore Running', '5', 338, '0:26:35', '151', '165', '3.3', '172', '179', '5:19', '4:18', '16', '13', 1.09, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '00:01.3', 6, '0:26:34', '0:26:35', '18', '28', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (39, 'Running', '4/21/2021', '17:45', 'Singapore Running', '7.55', 439, '0:34:31', '156', '178', '3.8', '166', '187', '4:34', '3:30', '22', '26', 1.3, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '00:00.7', 13, '0:34:00', '0:34:31', '71', '79', 2) ;

INSERT INTO training(id, activitytype, date, time, title, distance, calories, timetaken, avgHR, maxHR, aerobicTE, avgruncadence, maxruncadence, avgpace, bestpace, elevgain, elevloss, avgstridelength, avgverticalratio, avgverticaloscillation, avgbikecadence, maxbikecadence, normalizedpower, maxavgpower, avgpower, maxpower, totalstrokes, avgSWOLF, avgstrokerate, bestlaptime, numberoflaps, movingtime, elapsedtime, minelevation, maxelevation, athlete_ID) VALUES (40, 'Running', '4/19/2021', '18:56', 'Singapore Running', '0.75', 27, '02:36.7', '132', '143', '0.6', '184', '225', '3:28', '2:13', '4', '5', 1.57, 0, 0, '--', '--', '--', '--', '--', '--', '--', '--', '--', '02:36.7', 1, '0:02:32', '02:36.7', '-62', '-56', 2) ;